spring:
  application:
    name: msclientes

server:
  port: 0

#Define em qual servidor registrar a instancia
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
